In [1]:
import numpy as np 

In [2]:
np.array([2,4,56,422,32,1])

array([  2,   4,  56, 422,  32,   1])

In [3]:
a=np.array([2,4,56,422,32,1])

In [4]:
a

array([  2,   4,  56, 422,  32,   1])

In [5]:
print(a)

[  2   4  56 422  32   1]


In [6]:
type(a)

numpy.ndarray

In [8]:
new=np.array([[45,34,22,2],[24,55,3,22]])

In [9]:
new

array([[45, 34, 22,  2],
       [24, 55,  3, 22]])

In [10]:
type(new)

numpy.ndarray

In [11]:
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])


array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [12]:
np.array([11,23,44] ,dtype=float)

array([11., 23., 44.])

In [13]:
np.array([11,23,44] ,dtype=bool)

array([ True,  True,  True])

In [14]:
np.array([11,23,44] ,dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [15]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [17]:
np.arange(1,21).reshape(5,4
                       )

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.random.random((4,3))

array([[0.67806425, 0.35336221, 0.18208766],
       [0.27043764, 0.43276986, 0.80188919],
       [0.92475372, 0.3971764 , 0.66019667],
       [0.28934865, 0.35863453, 0.37703415]])

In [28]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
np.linspace(2,3,10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [31]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [32]:
data=np.array([1,2,3])
data[1]

2

In [34]:
data[0:2]

array([1, 2])

In [35]:
data[1:]

array([2, 3])

In [36]:
data[-2:]

array([2, 3])

In [37]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<5])

[1 2 3 4]


In [38]:
five_up=(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [40]:
divisiblebytwo=(a%2==0)
print(a[divisiblebytwo])

[ 2  4  6  8 10 12]


In [41]:
c=a[(a<7) & (a>2)]

In [42]:
c

array([3, 4, 5, 6])

In [43]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a.ndim


2

In [44]:
a.size

12

In [45]:
a.shape

(3, 4)

In [4]:
import numpy as np


In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
a1=np.arange (10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a2=np.arange(12,dtype=float).reshape(3,4)

In [10]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
arr=[[[0,1],[2,3]],[[4,5],[6,7]]]

In [13]:
arr

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
a1.shape

(10,)

In [18]:
a2.shape

(3, 4)

In [19]:
a3.shape

(2, 2, 2)

In [20]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a3.size

8

In [22]:
a2.size

12

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1.itemsize

4

In [26]:
a2.itemsize

8

In [27]:
a3.itemsize

4

In [28]:
print(a1.dtype)

int32


In [29]:
print(a2.dtype)

float64


In [30]:
print(a3.dtype)

int32


In [31]:
x=np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [32]:
x.astype(int
        )

array([33, 22,  2])

In [33]:
x.astype(float)

array([33. , 22. ,  2.5])

In [34]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [35]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [38]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [39]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [41]:
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [42]:
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [43]:
z2>2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
z2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [45]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
z1+z2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [48]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [49]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [50]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [51]:
z1//z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
k1=np.random.random((3,3))
k1=np.round(k1*100)
k1

array([[69.,  1., 88.],
       [89., 82., 83.],
       [95., 87., 60.]])

In [58]:
np.max(k1)

95.0

In [59]:
np.min(k1)

1.0

In [60]:
np.sum(k1)

654.0

In [61]:
np.prod(k1)

1823928554923200.0

In [63]:
np.random.random((3,3))

array([[0.56882693, 0.09888407, 0.18602414],
       [0.32087153, 0.67570378, 0.18142626],
       [0.78659539, 0.85531047, 0.53284989]])

In [64]:
np.max(k1 ,axis=1)

array([88., 89., 95.])

In [65]:
np.max(k1,axis=0)

array([95., 87., 88.])

In [66]:
np.prod(k1,axis=0)

array([583395.,   7134., 438240.])

In [67]:
np.prod(k1,axis=1)

array([  6072., 605734., 495900.])

In [68]:
k1

array([[69.,  1., 88.],
       [89., 82., 83.],
       [95., 87., 60.]])

In [69]:
np.mean(k1)

72.66666666666667

In [70]:
np.mean(k1,axis=0)

array([84.33333333, 56.66666667, 77.        ])

In [71]:
np.mean(k1,axis=1)

array([52.66666667, 84.66666667, 80.66666667])

In [72]:
np.median(k1)

83.0

In [73]:
np.median(k1,axis=1)

array([69., 83., 87.])

In [74]:
np.std(k1)

27.304863221696525

In [75]:
np.std(k1,axis=0)

array([11.11555467, 39.4151691 , 12.19289411])

In [76]:
np.var(k1)

745.5555555555555

In [79]:
k1


array([[69.,  1., 88.],
       [89., 82., 83.],
       [95., 87., 60.]])

In [81]:
np.sin(k1)

array([[-0.11478481,  0.84147098,  0.0353983 ],
       [ 0.86006941,  0.31322878,  0.96836446],
       [ 0.68326171, -0.82181784, -0.30481062]])

In [82]:
np.cos(k1)

array([[ 0.99339038,  0.54030231,  0.99937328],
       [ 0.51017704,  0.9496777 ,  0.24954012],
       [ 0.73017356,  0.56975033, -0.95241298]])

In [83]:
np.tan(k1)

array([[-0.11554855,  1.55740772,  0.0354205 ],
       [ 1.68582537,  0.32982641,  3.88059631],
       [ 0.93575247, -1.44241747,  0.32004039]])

In [86]:
s1=np.arange(12).reshape(3,4)

In [87]:
s2=np.arange(12,24).reshape(4,3)

In [88]:
s1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
s2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [90]:
np.dot(s1,s2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [91]:
np.exp(s1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [92]:
arr=np.array([1,2,2.7,3.5,4.9])

In [93]:
round_arr=np.round(arr)

In [94]:
print(round_arr)

[1. 2. 3. 4. 5.]


In [96]:
arr=np.array([1,2.2984,2.725985,3.51828,4.912])
round_arr=np.round(arr,decimals=2)
print(round_arr)

[1.   2.3  2.73 3.52 4.91]


In [99]:
np.round(np.random.random((3,7))*100)

array([[44., 75., 14., 48., 21.,  9., 94.],
       [71., 79., 37., 90., 90., 73.,  3.],
       [27., 91., 90., 48., 99., 94., 87.]])

In [100]:
arr=np.array([1,2,2.7,3.5,4.9])
floor_arr=np.floor(arr)
print(floor_arr)

[1. 2. 2. 3. 4.]


In [102]:
np.floor(np.random.random((2,3))*100)

array([[31., 97., 23.],
       [11., 95., 58.]])

In [103]:
arr=np.array([1,2.2984,2.725985,3.51828,4.912])
ceil_array=np.ceil(arr)
print(ceil_array)

[1. 3. 3. 4. 5.]


In [104]:
p1=np.arange(10)

In [105]:
p2=np.arange(12).reshape(3,4)
p3=np.arange(8).reshape(2,2,2)

In [106]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
p3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [109]:
p1[-1]

9

In [110]:
p1[0]

0

In [111]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
p2[1,2]

6

In [113]:
p2[2,3]

11

In [114]:
p2[1,0]

4

In [115]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [116]:
p3[1,0,1]

5

In [117]:
p3[0,1,0]

2

In [118]:
p3[0,0,0]

0

In [119]:
p3[1,1,0]

6

In [120]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
p1[2:5]

array([2, 3, 4])

In [122]:
p1[2:5:2]

array([2, 4])

In [124]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
p2[0,:]

array([0, 1, 2, 3])

In [128]:
p2[:,2]

array([ 2,  6, 10])

In [129]:
p2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [131]:
p2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [132]:
p2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [133]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
p2[1,0::3]

array([4, 7])

In [137]:
p2[:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [138]:
p2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [142]:
p2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [143]:
p3=np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [144]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [145]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [147]:
p3[0,1,:]

array([3, 4, 5])

In [148]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [149]:
p3[1,:,1]

array([10, 13, 16])

In [150]:
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [151]:
p3[0,0,0::2]

array([0, 2])

In [152]:
p3[2,0,0::2]

array([18, 20])

In [154]:
p3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [155]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [157]:
p2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [159]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [160]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [161]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [163]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [165]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [166]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [167]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [168]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [170]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [177]:
w1=np.arange(12).reshape(3,4)

In [178]:
w2=np.arange(12,24).reshape(3,4)

In [179]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [181]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [182]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [183]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [185]:
np.hsplit(w1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [189]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [4]:
import numpy as np
w=np.arange(12).reshape(4,3)
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
w[1,2]

5

In [6]:
w[1:3,1:]

array([[4, 5],
       [7, 8]])

In [7]:
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
w[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
z=np.arange(24).reshape(6,4)

In [11]:
z[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [12]:
z[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [13]:
G=np.random.randint(1,100,24).reshape(6,4)

In [16]:
G

array([[48, 12, 98, 35],
       [64, 45, 89, 95],
       [ 7, 70, 34, 54],
       [31, 93, 98, 63],
       [28, 96,  7, 77],
       [21, 73, 61, 69]])

In [17]:
G>50

array([[False, False,  True, False],
       [ True, False,  True,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True]])

In [18]:
G[G>50]

array([98, 64, 89, 95, 70, 54, 93, 98, 63, 96, 77, 73, 61, 69])

In [19]:
G%2==0

array([[ True,  True,  True, False],
       [ True, False, False, False],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [20]:
G[G%2==0]

array([48, 12, 98, 64, 70, 34, 54, 98, 28, 96])

In [23]:
G[(G%2==0) & (G >50)]

array([98, 64, 70, 54, 98, 96])

In [24]:
G[(G/7)!=0]

array([48, 12, 98, 35, 64, 45, 89, 95,  7, 70, 34, 54, 31, 93, 98, 63, 28,
       96,  7, 77, 21, 73, 61, 69])

In [25]:
G[~(G%7 == 0)]

array([48, 12, 64, 45, 89, 95, 34, 54, 31, 93, 96, 73, 61, 69])

In [28]:
a=np.random.randint(1,100,15)
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [29]:
np.sort(a)

array([ 7, 16, 18, 28, 30, 32, 37, 38, 50, 56, 62, 67, 90, 97, 98])

In [30]:
np.sort(a)[::-1]

array([98, 97, 90, 67, 62, 56, 50, 38, 37, 32, 30, 28, 18, 16,  7])

In [31]:
b=np.random.randint(1,100,24).reshape(6,4)

In [32]:
np.sort(b)

array([[75, 80, 82, 88],
       [47, 48, 75, 91],
       [ 5, 40, 58, 70],
       [15, 20, 57, 58],
       [29, 57, 63, 92],
       [21, 50, 57, 57]])

In [33]:
np.sort(b,axis=0)

array([[40, 20, 15,  5],
       [57, 47, 21, 29],
       [58, 50, 48, 57],
       [63, 57, 70, 57],
       [75, 58, 75, 88],
       [80, 82, 92, 91]])

In [34]:
np.sort(b,axis=1)

array([[75, 80, 82, 88],
       [47, 48, 75, 91],
       [ 5, 40, 58, 70],
       [15, 20, 57, 58],
       [29, 57, 63, 92],
       [21, 50, 57, 57]])

In [35]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [36]:
np.append(a,200)

array([ 98,  62,  18,  90,  56,  37,  97,  38,   7,  32,  50,  67,  16,
        28,  30, 200])

In [37]:
b

array([[80, 82, 75, 88],
       [75, 47, 48, 91],
       [40, 58, 70,  5],
       [58, 20, 15, 57],
       [63, 57, 92, 29],
       [57, 50, 21, 57]])

In [38]:
b.shape

(6, 4)

In [39]:
b.shape[0]

6

In [40]:
np.ones((b.shape[0],1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [41]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[80., 82., 75., 88.,  1.],
       [75., 47., 48., 91.,  1.],
       [40., 58., 70.,  5.,  1.],
       [58., 20., 15., 57.,  1.],
       [63., 57., 92., 29.,  1.],
       [57., 50., 21., 57.,  1.]])

In [46]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[80.        , 82.        , 75.        , 88.        ,  0.37517544],
       [75.        , 47.        , 48.        , 91.        ,  0.78621692],
       [40.        , 58.        , 70.        ,  5.        ,  0.40944222],
       [58.        , 20.        , 15.        , 57.        ,  0.80558231],
       [63.        , 57.        , 92.        , 29.        ,  0.60578603],
       [57.        , 50.        , 21.        , 57.        ,  0.11677568]])

In [48]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

In [49]:
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [50]:
np.concatenate((c,d))

TypeError: only integer scalar arrays can be converted to a scalar index

In [51]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [53]:
e=np.array([1,1,22,3,3,44,5,6,77,4,4,2,2])

In [56]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6, 22, 44, 77])

In [57]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [58]:
a.shape

(15,)

In [61]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [62]:
np.expand_dims(a,axis=0)

array([[98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30]])

In [63]:
np.expand_dims(a,axis = 1)

array([[98],
       [62],
       [18],
       [90],
       [56],
       [37],
       [97],
       [38],
       [ 7],
       [32],
       [50],
       [67],
       [16],
       [28],
       [30]])

In [64]:
np.expand_dims(a,axis = 1).shape

(15, 1)

In [65]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [66]:
np.where(a>50)

(array([ 0,  1,  3,  4,  6, 11], dtype=int64),)

In [67]:
np.where(a>50,0,a)

array([ 0,  0, 18,  0,  0, 37,  0, 38,  7, 32, 50,  0, 16, 28, 30])

In [68]:
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0,  0, 37, 97,  0,  7,  0,  0, 67,  0,  0,  0])

In [69]:
a


array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [71]:
a.max()

98

In [72]:
a.argmax()

0

In [73]:
b


array([[80, 82, 75, 88],
       [75, 47, 48, 91],
       [40, 58, 70,  5],
       [58, 20, 15, 57],
       [63, 57, 92, 29],
       [57, 50, 21, 57]])

In [74]:
np.argmax(a)

0

In [75]:
b


array([[80, 82, 75, 88],
       [75, 47, 48, 91],
       [40, 58, 70,  5],
       [58, 20, 15, 57],
       [63, 57, 92, 29],
       [57, 50, 21, 57]])

In [76]:
np.argmax(b,axis=1)

array([3, 3, 2, 0, 2, 0], dtype=int64)

In [77]:
np.argmax(b,axis=0)

array([0, 0, 4, 1], dtype=int64)

In [78]:
a


array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [79]:
np.argmin(a)

8

In [80]:
np.argmin(b,axis=1)

array([2, 1, 3, 2, 3, 2], dtype=int64)

In [81]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [82]:
np.cumsum(a)

array([ 98, 160, 178, 268, 324, 361, 458, 496, 503, 535, 585, 652, 668,
       696, 726])

In [83]:
b

array([[80, 82, 75, 88],
       [75, 47, 48, 91],
       [40, 58, 70,  5],
       [58, 20, 15, 57],
       [63, 57, 92, 29],
       [57, 50, 21, 57]])

In [84]:
np.cumsum(b,axis=0)

array([[ 80,  82,  75,  88],
       [155, 129, 123, 179],
       [195, 187, 193, 184],
       [253, 207, 208, 241],
       [316, 264, 300, 270],
       [373, 314, 321, 327]])

In [85]:
np.cumsum(b,axis=1)

array([[ 80, 162, 237, 325],
       [ 75, 122, 170, 261],
       [ 40,  98, 168, 173],
       [ 58,  78,  93, 150],
       [ 63, 120, 212, 241],
       [ 57, 107, 128, 185]])

In [86]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [87]:
np.cumprod(a)

array([         98,        6076,      109368,     9843120,   551214720,
       -1079891840, -1670293376,   953361152, -1916406528, -1195466752,
         356204544, -1904099328,  -400818176,  1661992960, -1679818752])

In [88]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [89]:
np.percentile(a,100)

98.0

In [90]:
np.percentile(a,0)

7.0

In [91]:
np.percentile(a,50)

38.0

In [92]:
np.percentile(a,75)

64.5

In [93]:
 np.percentile(a,10)

16.8

In [94]:
np.median(a)

38.0

In [95]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [96]:
items=[10,20,30,40,98]

In [97]:
np.isin(a,items)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [98]:
a

array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [99]:
np.flip(a)

array([30, 28, 16, 67, 50, 32,  7, 38, 97, 37, 56, 90, 18, 62, 98])

In [100]:
b

array([[80, 82, 75, 88],
       [75, 47, 48, 91],
       [40, 58, 70,  5],
       [58, 20, 15, 57],
       [63, 57, 92, 29],
       [57, 50, 21, 57]])

In [101]:
np.flip(b)

array([[57, 21, 50, 57],
       [29, 92, 57, 63],
       [57, 15, 20, 58],
       [ 5, 70, 58, 40],
       [91, 48, 47, 75],
       [88, 75, 82, 80]])

In [102]:
np.flip(b,axis=1)

array([[88, 75, 82, 80],
       [91, 48, 47, 75],
       [ 5, 70, 58, 40],
       [57, 15, 20, 58],
       [29, 92, 57, 63],
       [57, 21, 50, 57]])

In [103]:
np.flip(b,axis=0)

array([[57, 50, 21, 57],
       [63, 57, 92, 29],
       [58, 20, 15, 57],
       [40, 58, 70,  5],
       [75, 47, 48, 91],
       [80, 82, 75, 88]])

In [104]:
a



array([98, 62, 18, 90, 56, 37, 97, 38,  7, 32, 50, 67, 16, 28, 30])

In [105]:
np.put(a,[0,1],[110,530])

In [106]:
a

array([110, 530,  18,  90,  56,  37,  97,  38,   7,  32,  50,  67,  16,
        28,  30])

In [107]:
np.delete(a,0)

array([530,  18,  90,  56,  37,  97,  38,   7,  32,  50,  67,  16,  28,
        30])

In [108]:
np.delete(a,[1,3,4])

array([110,  18,  37,  97,  38,   7,  32,  50,  67,  16,  28,  30])