In [1]:
import numpy as np 

In [2]:
np.array([2,4,56,422,32,1])

array([  2,   4,  56, 422,  32,   1])

In [3]:
a=np.array([2,4,56,422,32,1])

In [4]:
a

array([  2,   4,  56, 422,  32,   1])

In [5]:
print(a)

[  2   4  56 422  32   1]


In [6]:
type(a)

numpy.ndarray

In [8]:
new=np.array([[45,34,22,2],[24,55,3,22]])

In [9]:
new

array([[45, 34, 22,  2],
       [24, 55,  3, 22]])

In [10]:
type(new)

numpy.ndarray

In [11]:
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])


array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [12]:
np.array([11,23,44] ,dtype=float)

array([11., 23., 44.])

In [13]:
np.array([11,23,44] ,dtype=bool)

array([ True,  True,  True])

In [14]:
np.array([11,23,44] ,dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [15]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [17]:
np.arange(1,21).reshape(5,4
                       )

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.random.random((4,3))

array([[0.67806425, 0.35336221, 0.18208766],
       [0.27043764, 0.43276986, 0.80188919],
       [0.92475372, 0.3971764 , 0.66019667],
       [0.28934865, 0.35863453, 0.37703415]])

In [28]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
np.linspace(2,3,10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [31]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [32]:
data=np.array([1,2,3])
data[1]

2

In [34]:
data[0:2]

array([1, 2])

In [35]:
data[1:]

array([2, 3])

In [36]:
data[-2:]

array([2, 3])

In [37]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<5])

[1 2 3 4]


In [38]:
five_up=(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [40]:
divisiblebytwo=(a%2==0)
print(a[divisiblebytwo])

[ 2  4  6  8 10 12]


In [41]:
c=a[(a<7) & (a>2)]

In [42]:
c

array([3, 4, 5, 6])